#!/usr/bin/env python3
"""
Step 1b: RUNTIME capture of the values that actually cross the neural/symbolic
interface while the library's own test suite executes.

Why this file exists
--------------------
An earlier version of this study inferred the tested belief range by parsing the
test sources with `ast`. That is a static heuristic and cannot support a claim
about what the tests *exercise*: it misses values built at runtime
(`random.random()`, `np.linspace`, a helper function, a `@parametrize` argument
generated by a call), it can pick up numeric lists that are not beliefs at all,
and it cannot tell whether a literal it found was ever executed (`if False:`
still parses).

This file replaces that inference with a measurement. It monkeypatches the two
points where a value actually crosses the interface, runs the suite in-process,
and records every value that passed through, tagged with the test that was
running at the time.

Probe A -- PRODUCED:  deepproblog.network.Network.__call__
    what the neural side emitted, per network.

Probe B -- CONSUMED:  deepproblog.semiring.graph_semiring.GraphSemiring.value
    what the symbolic side actually read into the semiring. This covers the
    neural path AND the `t(_)` probabilistic-parameter path AND stored tensors,
    so it is the true "what crossed into the algebra" measurement.

Role classification is read off the live Network object, not guessed:
    net.det is True            -> nn/3 deterministic predicate (output is an
                                  ordinary tensor, NOT a belief; any real value
                                  is legitimate)
    net.domain is not None     -> nn/4 annotated disjunction (must be a
                                  distribution over the domain)
    otherwise                  -> nn/2 probabilistic fact (must be in [0,1])

Usage:
    python instrument_tests.py                # instrument deepproblog's suite
    python instrument_tests.py --test-root DIR

Writes results/runtime_interface_trace.json
"""
from __future__ import annotations

import argparse
import json
import math
import os
import pathlib
import sys
import time
from collections import Counter, defaultdict

HERE = pathlib.Path(__file__).resolve().parent
RESULTS = HERE / "results"
RESULTS.mkdir(exist_ok=True)

OBSERVATIONS: list[dict] = []


def _current_test() -> str:
    """pytest exports the running test id here; format is
    'path::test_name (call)'."""
    return os.environ.get("PYTEST_CURRENT_TEST", "<outside a test>").split(" (")[0]


def _summarise(t) -> dict | None:
    """Reduce a tensor/list/scalar to the facts the study needs. Returns None
    for things that are not numeric at all."""
    import torch

    if isinstance(t, torch.Tensor):
        flat = t.detach().reshape(-1).tolist()
        dtype, shape = str(t.dtype), list(t.shape)
        requires_grad = bool(t.requires_grad)
    elif isinstance(t, (list, tuple)):
        flat, dtype, shape, requires_grad = [], None, [len(t)], None
        for x in t:
            sub = _summarise(x)
            if sub is None:
                return None
            flat.extend(sub["values"])
            dtype = dtype or sub["dtype"]
        shape = [len(t)]
    elif isinstance(t, (int, float)) and not isinstance(t, bool):
        flat, dtype, shape, requires_grad = [float(t)], type(t).__name__, [], None
    else:
        return None

    if not flat:
        return {"values": [], "dtype": dtype, "shape": shape, "n": 0,
                "min": None, "max": None, "sum": None, "has_nan": False,
                "has_inf": False, "in_unit_interval": None, "sums_to_one": None,
                "requires_grad": requires_grad}

    has_nan = any(math.isnan(x) for x in flat)
    has_inf = any(math.isinf(x) for x in flat)
    finite = [x for x in flat if math.isfinite(x)]
    s = sum(finite) if finite else None
    return {
        "values": flat[:16],           # cap, full stats are below
        "dtype": dtype, "shape": shape, "n": len(flat),
        "min": min(finite) if finite else None,
        "max": max(finite) if finite else None,
        "sum": s,
        "has_nan": has_nan, "has_inf": has_inf,
        "in_unit_interval": (not has_nan and not has_inf
                             and all(0.0 <= x <= 1.0 for x in flat)),
        "sums_to_one": (s is not None and abs(s - 1.0) < 1e-6),
        "requires_grad": requires_grad,
    }


def _role_of(net) -> str:
    if getattr(net, "det", False):
        return "nn/3 deterministic (tensor, not a belief)"
    if getattr(net, "domain", None) is not None:
        return "nn/4 annotated disjunction (must be a distribution)"
    return "nn/2 probabilistic fact (must be in [0,1])"


def install_probes():
    """Patch the two crossing points. Returns an uninstall callable."""
    from deepproblog.network import Network
    from deepproblog.semiring.graph_semiring import GraphSemiring

    orig_call = Network.__call__
    orig_value = GraphSemiring.value

    def probed_call(self, to_evaluate):
        out = orig_call(self, to_evaluate)
        summary = _summarise(out)
        if summary is not None:
            OBSERVATIONS.append({
                "probe": "produced", "network": self.name,
                "role": _role_of(self), "test": _current_test(),
                "batching": bool(getattr(self, "batching", False)),
                "eval_mode": bool(getattr(self, "eval_mode", False)),
                **summary,
            })
        return out

    def probed_value(self, a, key=None):
        out = orig_value(self, a, key)
        summary = _summarise(out)
        if summary is not None:
            # Group by the KIND of term, not by its value: a Constant's functor
            # is the number itself, which would give one group per literal.
            functor = getattr(a, "functor", None)
            if isinstance(functor, str) and functor in ("nn", "t", "tensor", "'/'"):
                kind = f"semiring.value <{functor}>"
            elif isinstance(functor, str):
                kind = f"semiring.value <term {functor}>"
            else:
                kind = "semiring.value <numeric constant>"
            OBSERVATIONS.append({
                "probe": "consumed", "network": None, "role": kind,
                "term_functor": str(functor), "test": _current_test(), **summary,
            })
        return out

    Network.__call__ = probed_call
    GraphSemiring.value = probed_value

    def uninstall():
        Network.__call__ = orig_call
        GraphSemiring.value = orig_value

    return uninstall


def analyse() -> dict:
    """Turn the raw trace into the statistics the study actually claims."""
    by_role = defaultdict(list)
    for o in OBSERVATIONS:
        by_role[o["role"]].append(o)

    roles = {}
    for role, obs in sorted(by_role.items()):
        flat = []
        for o in obs:
            flat.extend(o["values"])
        finite = [x for x in flat if math.isfinite(x)]
        # distribution, not just min/max -- the reviewer's point
        uniq = sorted(set(round(x, 12) for x in finite))
        qs = {}
        if finite:
            srt = sorted(finite)
            for q in (0, 5, 25, 50, 75, 95, 100):
                qs[f"p{q}"] = srt[min(len(srt) - 1, int(q / 100 * (len(srt) - 1)))]
        roles[role] = {
            "observations": len(obs),
            "distinct_tests": len(set(o["test"] for o in obs)),
            "vector_dimensions": dict(Counter(o["n"] for o in obs)),
            "dtypes": dict(Counter(str(o["dtype"]) for o in obs)),
            "n_values_sampled": len(flat),
            "n_distinct_values": len(uniq),
            "min": min(finite) if finite else None,
            "max": max(finite) if finite else None,
            "quantiles": qs,
            "observations_with_nan": sum(1 for o in obs if o["has_nan"]),
            "observations_with_inf": sum(1 for o in obs if o["has_inf"]),
            "observations_entirely_in_unit_interval": sum(
                1 for o in obs if o["in_unit_interval"]),
            "observations_outside_unit_interval": sum(
                1 for o in obs if o["in_unit_interval"] is False),
            "observations_summing_to_one": sum(1 for o in obs if o["sums_to_one"]),
        }

    # The headline question, restricted to the roles where a belief must be a
    # probability. nn/3 deterministic outputs are excluded because an ordinary
    # tensor is legitimately any real.
    belief_roles = [r for r in by_role
                    if r.startswith("nn/2") or r.startswith("nn/4")]
    belief_obs = [o for r in belief_roles for o in by_role[r]]
    bflat = [x for o in belief_obs for x in o["values"]]
    bfin = [x for x in bflat if math.isfinite(x)]

    return {
        "by_role": roles,
        "belief_position_summary": {
            "roles_counted": belief_roles,
            "observations": len(belief_obs),
            "values_sampled": len(bflat),
            "min": min(bfin) if bfin else None,
            "max": max(bfin) if bfin else None,
            "any_negative": any(x < 0 for x in bfin),
            "any_above_one": any(x > 1 for x in bfin),
            "any_nan": any(math.isnan(x) for x in bflat),
            "any_inf": any(math.isinf(x) for x in bflat),
            "observations_outside_unit_interval": sum(
                1 for o in belief_obs if o["in_unit_interval"] is False),
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--test-root", default=None,
                    help="directory of tests to run (default: deepproblog's own)")
    args = ap.parse_args()

    import pytest
    import deepproblog

    root = args.test_root or str(pathlib.Path(deepproblog.__file__).parent / "tests")

    uninstall = install_probes()
    t0 = time.time()
    code = pytest.main([root, "-q", "--no-header", "-p", "no:cacheprovider"])
    elapsed = time.time() - t0
    uninstall()

    analysis = analyse()
    payload = {
        "generated": time.strftime("%Y-%m-%d %H:%M:%S"),
        "method": "runtime monkeypatch of Network.__call__ and GraphSemiring.value "
                  "during in-process execution of the library's own pytest suite",
        "test_root": root,
        "pytest_exit_code": int(code),
        "seconds": round(elapsed, 2),
        "total_observations": len(OBSERVATIONS),
        "analysis": analysis,
        "trace": OBSERVATIONS,
    }
    (RESULTS / "runtime_interface_trace.json").write_text(
        json.dumps(payload, indent=1, default=str))

    print("\n" + "=" * 78)
    print(f"RUNTIME INTERFACE TRACE -- {len(OBSERVATIONS)} observations "
          f"in {elapsed:.1f}s")
    print("=" * 78)
    for role, st in analysis["by_role"].items():
        print(f"\n{role}")
        print(f"  observations {st['observations']:<5} "
              f"across {st['distinct_tests']} tests   "
              f"dims {st['vector_dimensions']}")
        print(f"  range [{st['min']}, {st['max']}]   "
              f"distinct values {st['n_distinct_values']}")
        print(f"  outside [0,1]: {st['observations_outside_unit_interval']}   "
              f"NaN: {st['observations_with_nan']}   "
              f"inf: {st['observations_with_inf']}   "
              f"sum==1: {st['observations_summing_to_one']}")
    b = analysis["belief_position_summary"]
    print("\n" + "-" * 78)
    print("BELIEF POSITION ONLY (nn/2 facts + nn/4 annotated disjunctions):")
    print(f"  {b['observations']} observations, {b['values_sampled']} values")
    print(f"  range [{b['min']}, {b['max']}]")
    print(f"  any negative: {b['any_negative']}   any > 1: {b['any_above_one']}   "
          f"NaN: {b['any_nan']}   inf: {b['any_inf']}")
    print(f"\nwrote {RESULTS / 'runtime_interface_trace.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
